development:
  protocol: 'http'
  host: localhost
  port: 5984
  prefix: zipasaurus

production:
  protocol: 'https'
  host: eignerchris.cloudant.com
  port: 443
  prefix: zipasaurus
  username: eignerchris
  password: thereisnospoon